title = "ユーラシアの風 – Blowin' in the Eurasian Wind -"
baseURL = "https://www.eawind.net/"
languageCode = "ja"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-MH3R1K53HT"
enableRobotsTXT = true

#[languages]
#  [languages.ja]
#    title = "Ananke"
#    weight = 1
#    contentDir = "content/ja"
#    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "eawind"
  favicon = "favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  recent_posts_number = 3
  body_classes = "system-sans-serif bg-light-gray"
  post_content_classes = "system-sans-serif"
  date_format = "2006/1/2 15:04:05"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/eawind"