baseURL = "http://www.eawind.net/"
languageCode = "ja"
title = "ユーラシアの風 – Blowin' in the Eurasian Wind -"
theme = "ananke"

googleAnalytics = "UA-2521488-1"

[params]
favicon = "favicon.ico"
featured_image = "/img/wp/2006/01/2003020509083411.jpg"
